name = "GeophysicalDissipation"
uuid = "631d5d2f-4fa6-4fbc-8b26-2b57e7a6c3a5"
authors = ["Gregory Wagner <wagner.greg@gmail.com>"]
version = "0.1.0"

[deps]
CLIMAParameters = "6eacf6c3-8458-43b9-ae03-caf5306d3d53"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
